version: "3"
services:
  demo-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000 # ホストマシンのポート8000を、docker内のポート8000に接続する
    environment:
      - WATCHFILES_FORCE_POLLING=true # 環境によってホットリロードのために必要
  db:
    image: "mysql/mysql-server:8.0"
    ports:
      - "33306:3306"
    environment:
      # MYSQL_ROOT_PASSWORD: "dbpassword"
      MYSQL_HOST: "%"
      MYSQL_DATABASE: "demo"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "dbpassword"
      MYSQL_PORT: "3306"
      MYSQL_CHARSET: "utf8mb4"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    # volumes:
    #   - "mysql_data:/var/lib/mysql"
volumes:
  mysql_data:
